# Generated by Django 5.1 on 2024-12-01 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_all_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_posts',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
