# Generated by Django 5.1 on 2024-12-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_all_posts_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_posts',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
