# Generated by Django 5.1 on 2024-12-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_all_posts_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_posts',
            name='Follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all_posts',
            name='Like',
            field=models.BooleanField(default=False),
        ),
    ]
