# Generated by Django 5.1 on 2024-12-03 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_all_posts_follow_all_posts_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_posts',
            name='Follow',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.all_posts')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
