# Generated by Django 5.1 on 2024-12-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_all_posts_id_alter_follow_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_posts',
            name='Like',
        ),
    ]
